### PR TITLE
Use configuration from users config

### PR DESCRIPTION
**Pull request by knownasilya**
Regards form Boston Ember :+1:

### CODE REVIEW

**Comment by patricksrobertson** [comment]
It's possible to set a config in this addon, but what I really need is access to the configuration in the application this addon is included in.

Two reasons for this:

* I have different hosts per environment that build based on the `ember build` command in the included application (my services have a training/staging/production host). This doesn't change from app to app, but I don't think the app pipeline is sufficiently advanced to build config dependencies of the addon from the included apps build command.
* I need a specific key per application for some things (the OAuth.js key) that can't live here either.

**Comment by knownasilya** [comment]
`this.container.lookup('config:environment')` should do it.

**Comment by patricksrobertson** [comment]
That is exactly what I'm looking for then :). Thanks!

**Comment by knownasilya** [comment]
Feel free to close this.

**Pull request closed without merging**
